version: "3.9"

services:
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server
    container_name: llama-server
    #platform: linux/arm64
    ports:
      - "8080:8080"
    volumes:
      - ./LLM/models:/models
    command: -m /models/qwen2.5-0.5b-instruct-q4_k_m.gguf

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "6872:6872"
    environment:
      - LLM_URL=http://llama-server:8080
    depends_on:
      - llama-server
    command: poetry run fastapi dev app/api/main.py --host 0.0.0.0 --port 6872

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "8502:8502"
    environment:
      - BACKEND_URL=http://backend:6872
    depends_on:
      - backend
    command: poetry run streamlit run app/web/streamlit_app.py --server.port=8502 --server.address=0.0.0.0