FROM python:3.10-slim
WORKDIR /app
COPY pyproject.toml poetry.lock ./
RUN pip install poetry && poetry install --no-root
COPY app/ ./app/
CMD ["poetry", "run", "fastapi", "dev", "app/api/main.py", "--host", "0.0.0.0", "--port", "6872"]