# fly.toml app configuration file generated for vladimv-morozov-new-classifier on 2025-07-22T02:01:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vladimv-morozov-new-classifier'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile.backend'

[http_service]
  internal_port = 6872
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '3gb'
  cpu_kind = 'shared'
  cpus = 2
